use std::collections::HashMap;
use std::net::Ipv4Addr;
use tokio::sync::mpsc;

use crate::dta::{Event, TelemetryPayload, Tracker};

pub(crate) fn NewTracker(tx: mpsc::Sender<TelemetryPayload>) -> Tracker {
    Tracker {
        scores: HashMap::new(),
        tx,
    }
}

// Helper to safely parse C-strings from the kernel
fn parse_c_string(bytes: &[u8]) -> String {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    String::from_utf8_lossy(&bytes[..end]).into_owned()
}

pub(crate) fn Evaluate(tracker: &mut Tracker, event: &Event) {
    let event_type = event.event_type;
    let pid = event.pid;
    let ppid = event.ppid;
    let uid = event.uid;
    let dest_ip = event.dest_ip;
    let dest_port = event.dest_port;
    let comm_bytes = event.comm;
    let filename_bytes = event.filename;

    let comm_string = parse_c_string(&comm_bytes);
    let filename = parse_c_string(&filename_bytes);
    
    // Parse IP and Port (Convert from Network Byte Order)
    let ip = Ipv4Addr::from(u32::from_be(dest_ip)).to_string();
    let port = u16::from_be(dest_port);

    // ==========================================
    // 🛑 THE NOISE & OBSERVER FILTER 🛑
    // ==========================================
    let comm = comm_string.to_lowercase();
    // 1. Drop our own infrastructure
    if comm.contains("tokio") || comm.contains("client") || comm.contains("genapi") { return; }
    
    // 2. Drop standard Linux background noise
    if comm.contains("dockerd") || comm.contains("networkmanager") || comm.contains("systemd") || comm.contains("dns") { return; }
    
    // 3. Drop DNS lookups (Port 53) and internal database ports
    if port == 53 || port == 8080 || port == 8081 || port == 6333 || port == 5432 { return; }
    
    // 4. Drop standard user terminal noise
    if comm.contains("git") || comm.contains("zsh") || comm.contains("tail") || comm.contains("socket thread") || comm.contains("sudo") { 
        return; 
    }

    // 5. Drop generic thread pools (Browsers/Electron apps)
    if comm.starts_with("pool-") { return; }

    // 6. Drop Port 0 (Usually internal UDP/ICMP routing checks, not actual TCP exploits)
    if port == 0 { return; }

    // 7. Drop core kernel and boot daemons (Extremely low PIDs are safe)
    if pid < 1000 { return; }

    // ==========================================

    // ==========================================
    // 🛑 THE OBSERVER EFFECT FIX 🛑
    // ==========================================
    // Drop all traffic generated by our own security stack!
    if comm_string.contains("tokio") || comm_string.contains("client") || comm_string.contains("genapi") {
        return; 
    }
    // Drop all traffic targeting our internal infrastructure
    if port == 8080 || port == 8081 || port == 6333 || port == 5432 {
        return; 
    }
    // ==========================================

    // 1. Log locally using the safely aligned local variables
    if event_type == 2 {
        println!("⚙️  [EXECVE] UID {} executed {} via {}", uid, filename, comm_string);
    } else if event_type == 1 {
        if ip != "127.0.0.1" && ip != "127.0.0.53" {
            println!("🌐 [CONNECT] UID {} process {} connected to {}:{}", uid, comm_string, ip, port);
        }
    }

    // 2. Build the JSON Payload
    let payload = TelemetryPayload {
        event_type,
        pid,
        ppid,
        uid,
        comm: comm_string,
        filename: if event_type == 2 { filename } else { String::new() },
        dest_ip: if event_type == 1 { ip } else { String::new() },
        dest_port: if event_type == 1 { port } else { 0 },
    };

    // 3. Send it to the Go API
    if let Err(e) = tracker.tx.try_send(payload) {
        eprintln!("Rate limit hit or channel full: {}", e);
    }
}
